import { useId } from 'react';
function projectPoint(u, v) {
  const radius = 110 + 43 * Math.cos(v);
  const x = radius * Math.cos(u), y = radius * Math.sin(u), z = 43 * Math.sin(v);
  const yy = y * Math.cos(.9) - z * Math.sin(.9);
  const spin = -.45;
  return [200 + x * Math.cos(spin) - yy * Math.sin(spin), 200 + x * Math.sin(spin) + yy * Math.cos(spin)];
}
const pathFor = points => points.map((p, j) => `${j ? 'L' : 'M'}${p[0].toFixed(2)},${p[1].toFixed(2)}`).join(' ');
const rings = Array.from({ length: 64 }, (_, i) => pathFor(Array.from({ length: 97 }, (_, j) => projectPoint(i / 64 * Math.PI * 2, j / 96 * Math.PI * 2))));
const parallels = Array.from({ length: 18 }, (_, i) => pathFor(Array.from({ length: 129 }, (_, j) => projectPoint(j / 128 * Math.PI * 2, i / 18 * Math.PI * 2))));
export function Wireform() {
  return <svg className="wireform" viewBox="0 0 400 400" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth=".7">{rings.map((path, i) => <path key={i} d={path} opacity=".65" />)}{parallels.map((path, i) => <path key={`c${i}`} d={path} opacity=".4" />)}</g></svg>;
}
export default function ProjectArt({ type }) {
  const glowId = useId();
  if (type === 'feathercut') return <div className="feather-product-art" aria-hidden="true"><div className="feather-product-window"><div className="feather-window-bar"><span className="feather-window-name"><img src="/images/feathercut-emblem.png" alt="" />Feathercut</span><span>− &nbsp; □ &nbsp; ×</span></div><div className="feather-file-bar"><span>Purple Cloud Flying Chill-Out.mp4</span><span>Open video</span></div><div className="feather-workspace"><div className="feather-media"><div className="feather-cloud-video" /><div className="feather-filmstrip"><div className="feather-trim-handles" /></div><div className="feather-timecodes"><span>00:00.0</span><span>05:35.3</span></div><div className="feather-playback"><span>Ⅰ◁</span><span className="feather-play-icon">▶</span><span>▷Ⅰ</span><span>01:31.6 / 05:35.3</span><span>♪ ━━●</span></div></div><div className="feather-settings"><b>Trim selection</b><div className="feather-time-input"><span>In</span><strong>00:00.0</strong></div><div className="feather-time-input"><span>Out</span><strong>05:35.3</strong></div><div className="feather-set-buttons"><span>Set in</span><span>Set out</span></div><span className="feather-duration">Selected duration<strong>335.32 seconds</strong></span><div className="feather-crop">⌗ &nbsp; Crop frame</div><span className="feather-volume">Clip audio <span>100%</span></span><div className="feather-volume-line" /><span className="feather-export">↥ &nbsp; Export cut</span></div></div><div className="feather-window-footer">Clips ready · S to split · drag to reorder <span>⚙</span></div></div></div>;
  if (type === 'particle-vortex') return <svg viewBox="0 0 600 380" className="particle-art" aria-hidden="true"><defs><radialGradient id={glowId}><stop stopColor="#b09be2" stopOpacity=".35" /><stop offset="1" stopColor="#b09be2" stopOpacity="0" /></radialGradient></defs><circle cx="300" cy="190" r="180" fill={`url(#${glowId})`} />{Array.from({ length: 400 }, (_, i) => { const angle = i * 2.39996; const r = Math.sqrt(i / 400) * 180; return <circle key={i} cx={300 + Math.cos(angle + r / 55) * r} cy={190 + Math.sin(angle + r / 55) * r * .65} r={i % 7 === 0 ? 1.8 : .7} fill={i % 3 ? '#9d85d8' : '#e6d9fa'} opacity={.3 + (i % 6) / 9} />; })}<circle cx="300" cy="190" r="39" fill="#17151d" stroke="#9d85d8" strokeWidth=".8" /><text x="300" y="192" textAnchor="middle" fill="#d0bee9" fontSize="10" letterSpacing="3">ECHOES</text><text x="300" y="209" textAnchor="middle" fill="#d0bee9" fontSize="6" letterSpacing="2">OF THE VOID</text></svg>;
  if (type === 'orbital-gravity') return <svg viewBox="0 0 600 380" className="orbit-art" aria-hidden="true"><g transform="translate(300 190) rotate(-24)" fill="none" stroke="#acc6ca" strokeWidth=".65">{[70, 115, 165, 220].map((r, i) => <ellipse key={r} rx={r} ry={r * .56} opacity={.6 - i * .1} />)}<circle r="31" fill="#d4e3d8" stroke="none" /><circle cx="115" r="7" fill="#b998e2" stroke="none" /><circle cx="-185" cy="66" r="4" fill="#c7d7d8" stroke="none" /><path d="M-220 0 H220 M0 -123 V123" strokeDasharray="3 7" opacity=".2" /></g><text x="300" y="330" textAnchor="middle" fill="#aec4c5" fontSize="10" letterSpacing="5">CELESTIAL DRIFT</text></svg>;
  if (type === 'audio-harp') return <div className="audio-art" aria-hidden="true"><div className="audio-name">aether<span>SPATIAL AUDIO ENGINE</span></div><div className="wave-bars">{Array.from({ length: 65 }, (_, i) => <i key={i} style={{ height: `${12 + Math.abs(Math.sin(i * .23) * Math.cos(i * .09)) * 105}px` }} />)}</div><div className="audio-scale"><span>20 Hz</span><span>1 kHz</span><span>20 kHz</span></div></div>;
  if (type === 'pathtracer-sphere') return <div className="sphere-art" aria-hidden="true"><div className="render-grid" /><div className="render-sphere sphere-one" /><div className="render-sphere sphere-two" /><span>RADIANCE / REAL-TIME PATH TRACING</span></div>;
  return <div className="net-art" aria-hidden="true"><div className="net-label"><span>CLIENT 01</span><span>128 Hz</span><span>CLIENT 02</span></div><svg viewBox="0 0 600 220" fill="none"><path d="M40 60 H110 L130 25 L150 95 L175 60 H280 L300 150 L330 60 H560" stroke="#d1d49d" strokeWidth="2" /><path d="M40 155 H110 L130 120 L150 190 L175 155 H280 L300 65 L330 155 H560" stroke="#d1d49d" strokeWidth="1" opacity=".35" />{[110, 175, 280, 330, 430, 510].map(x => <path key={x} d={`M${x} 20 V200`} stroke="#d1d49d" opacity=".15" strokeDasharray="3 5" />)}</svg><span className="net-bottom">PREDICT. RECONCILE. REPEAT.</span></div>;
}


